# Generated by Django 3.1.7 on 2021-03-30 02:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_app', '0002_auto_20210329_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedBmrResults',
            new_name='SavedBmiResults',
        ),
    ]
