# Generated by Django 3.1.7 on 2021-03-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_auto_20210329_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbmiresults',
            name='bmi_result',
            field=models.FloatField(blank=True, default=0, verbose_name='bmiresult'),
        ),
    ]
